### PR TITLE
Some changes for better performance using SCSS

### PR DESCRIPTION
**Pull request by chichmagnetico**
- Read color-vid attribute from .video-container element to set the color for vimeo player
- Remove video controls from youtube.
- Switch scss
- Modify example
- Play icon over image of video previews
- Async stylesheet for better display of videos

### CODE REVIEW

**Comment by Mantish** [comment]
Hi,
Thanks for contributing.
I like some of your ideas but I won't merge it as we're trying to keep it simple

**Comment by chichmagnetico** [comment]
Don't worry, I know it did become a little less simpler.
I thought that in some occasions, at the end, it would become easier to implement the script this way to a bigger project. Feel free to use the ideas you like.

**Comment by chichmagnetico** [comment]
Por cierto, buen plugin :)

**Comment by Mantish** [comment]
Gracias!

**Pull request closed without merging**
